Add unko.ping
unkontributors/super_unko pull request #98
Opened 2021-09-16 09:20 UTC by Hayao0819

`unko.ping`コマンドを追加しました。unko.csvの一覧のドメインにPingを送信します。
相手のサーバへの負荷がかからないようにコマンドラインオプションを設定しています。
Batsのテストも作成しましたが、コマンドの特性上どうしても実行に時間がかかってしまうのでコメントアウトしてあります。
ShellCheckやLintはテスト済みです。READMEに説明を追加してあります。

## Check list

* [x] Were all tests passed of CI?
  * (Case: failing `test`) Please run tests and fix your code (see also: [Testing](https://github.com/unkontributors/super_unko/blob/oshiri/README.md#testing))
  * (Case: failing `format`) Please run `./linter.sh format-save` (see also: [CodeStyle and lint](https://github.com/unkontributors/super_unko/blob/oshiri/README.md#codestyle-and-lint))
  * (Case: failing `lint`) Please run linter and fix your code (see also: [CodeStyle and lint](https://github.com/unkontributors/super_unko/blob/oshiri/README.md#codestyle-and-lint))
*  [x] (Case: adding new command) Were tests added to cover new commands ?
*  [x] (Case: adding new command) Were descriptions for new commands added to README?

2021-09-20 16:09 UTC, greymd commented
ｗｗｗ
![Screenshot 2021-09-20 at 17 09 30](https://user-images.githubusercontent.com/3874767/134036134-ba2f1bfe-6363-42d5-aff8-908eed27c293.png)

2021-09-20 16:12 UTC, greymd requested changes

2021-09-20 16:12 UTC, greymd commented on bin/unko.ping
> +LIB_DIR="/usr/lib/super_unko"
`LIB_DIR` に 2 回代入していますが、後半の代入は不要じゃないですかね。

2021-09-20 16:32 UTC, greymd commented
メモ：
`ping`はマルチバイト文字が与えられたら勝手にpunycodeにしてくれる模様（知らなかった）。
最近のバージョンであればLinuxでもBSDでも大丈夫そう。

#### Linux (Ubuntu 18.04)

```
$ ping -c 1 -s 1 -W 0.25 うんこ.com
PING うんこ.com (157.7.44.218) 1(29) bytes of data.
9 bytes from users016.vip.heteml.jp (157.7.44.218): icmp_seq=1 ttl=26

--- うんこ.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
$ ping -V
ping utility, iputils-s20161105
```

#### macOS

```
$ ping -c 1 -s 1 -W 0.25 うんこ.com
PING xn--p8j0a9n.com (157.7.44.218): 1 data bytes
9 bytes from 157.7.44.218: icmp_seq=0 ttl=47

--- xn--p8j0a9n.com ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
$ man ping | tail -n 1
BSD                             March 29, 2013                             BSD
```

2021-09-20 17:39 UTC, greymd commented
メモ2: （`ping`の挙動調査）
`getaddrinfo`コールの際に `AI_IDN` が指定されているから、`うんこ.com`でも問題なくIDNフォーマットに変換されて`ping`が飛ばせるらしい。
https://man7.org/linux/man-pages/man3/getaddrinfo.3.html
>       AI_IDN If this flag is specified, then the node name given in
>              node is converted to IDN format if necessary.  The source
>              encoding is that of the current locale.
>
>              If the input name contains non-ASCII characters, then the
>              IDN encoding is used.  Those parts of the node name

iputils の ping には `getaddrinfo`フラグに `AI_IDN` が指定されているが、`USE_IDN` がないと Punycode 変換がされない。
しかし検証する限り最近のOSでは基本的に `USE_IDN` があるので、`うんこ.com` でもちゃんと `ping` が飛ばせるらしい。
https://github.com/iputils/iputils/blob/7b389d0c21f243ae10c87b43910609af70ae9f66/ping/ping.h#L45

ロケールがCのとき、`AI_CANONIDN` が外れるのが気になる。
https://github.com/iputils/iputils/blob/7b389d0c21f243ae10c87b43910609af70ae9f66/ping/ping.c#L298-L299

案の定、`LANG` によってエンコードが失敗するので、OS のロケールによっては `ping` ないし `unko.ping` は正常に動作しない。。

```
$ LANG=C ping -c 1 うんこ.com
ping: うんこ.com: Parameter string not correctly encoded
$ LANG=C ./unko.ping
Success ping to poo.com
```

明示的に UTF-8 を使うように指定してあげれば大丈夫そう。

```
$ LANG=C.UTF-8 ./unko.ping
Success ping to うんこ.com
Success ping to うんち.com
Success ping to poo.com
︙
```

2021-09-20 19:10 UTC, greymd requested changes

2021-09-20 19:10 UTC, greymd commented on bin/unko.ping
> +    ping -c 1 -s 1 -W 0.25 "${unko}.${tld}" 2> /dev/null 1>&2 && echo "Success ping to ${unko}.${tld}"
`LANG=C.UTF-8 ping -c 1 -s 1 -W 1 ..中略` のように変更できませんかね。

OS のロケール設定がマルチバイト文字じゃない環境、具体的には環境変数 `LANG=C` の環境の場合、この箇所は `うんこ.com` を読み込んだ際に失敗します（[別コメント](https://github.com/unkontributors/super_unko/pull/98#issuecomment-923137960)）

`LANG=C.UTF-8` を文頭に追加することで、`ping` のプロセスではマルチバイト文字のドメイン名も正常にエンコードできるようになります。

また、私の Ubuntu 18.04 の環境で試したところ`-W` オプションは整数のみを有効な値で読み込むようでした。そのため、下記のコマンドは延々とレスポンスを待ち続けてしまいます。

```
~ $ ping -c 1 -s 1 -W 0.25 feces.com
PING feces.com (52.128.23.153) 1(29) bytes of data.
!! 延々と待ち続ける
~ $ ping -c 1 -s 1 -W 0 feces.com
PING feces.com (52.128.23.153) 1(29) bytes of data.
!! -W 0 も延々と待ち続ける
```

設定できる最小値である `-W 1` とするのが良いと思います。

2021-09-22 13:03 UTC, Hayao0819 commented on bin/unko.ping
> +LIB_DIR="/usr/lib/super_unko"
デバッグ用に追加していたのをすっかり忘れていました。削除しました。

2021-09-22 13:04 UTC, Hayao0819 commented on bin/unko.ping
> +    ping -c 1 -s 1 -W 0.25 "${unko}.${tld}" 2> /dev/null 1>&2 && echo "Success ping to ${unko}.${tld}"
`LANG=C.UTF-8 ping -c 1 -s 1 -W 1`にしてみましたが、どうでしょうか？
おそらくこれで修正されていると思うのですが...

2021-09-22 13:05 UTC, Hayao0819 commented
バグの検証と提案ありがとうございます。指摘通り修正を行いました。

2021-09-22 22:12 UTC, greymd approved these changes

2021-09-22 22:16 UTC, greymd commented
```
＿人人人人人人人人人人人人人人人人＿
＞　unko.ping を oshiri に merge!　＜
￣Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^￣
　　　　　　👑
　　　　（💩💩💩）
　　　（💩👁💩👁💩）
　　（💩💩💩👃💩💩💩）
　（💩💩💩💩👄💩💩💩💩）
```

2021-09-22 22:16 UTC, merged